spring.application.name=scuola

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:inv_man
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=true

# Logging Configuration
logging.level.org.hibernate.SQL=INFO
logging.level.root=INFO
logging.file.name=logs/application.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %level - [%thread] %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %level - [%thread] %logger{36} - %msg%n

# JWT Configuration
myapp.jwtSecret=FAJ333NcRfUjXn2r5u8xAABDTGGKaPdSgVkYp3s6v9yBBUE9H0MbQeThWmZq4t7wHzFAJ333NcRfUjXn2r5u8xAABDTGGKaPdSgVkYp3s6v9yBBUE9H0MbQeThWmZq4t7wHz
myapp.jwtExpirationMs=86400000
